export const technologies = [
    { name: "HTML", thumbnail: 'html-5.webp' },
    { name: "CSS", thumbnail: 'css-3.webp' },
    { name: "Bootstrap", thumbnail: 'bootstrap.webp' },
    { name: "Tailwind", thumbnail: 'tailwind.png' },
    { name: "Git", thumbnail: 'git.webp' },
    { name: "SASS", thumbnail: 'sass.webp' },
    { name: "Javascript", thumbnail: 'js.webp' },
    { name: "Typescript", thumbnail: 'typescript.png' },
    { name: "React", thumbnail: 'reactjs.webp' },
    { name: "ReactNative", thumbnail: 'react-native.png' },
    { name: "Node", thumbnail: 'node.webp' },
    { name: "Express", thumbnail: 'express.webp' },
    { name: "Socket.IO", thumbnail: 'socketio.png' },
    { name: "Handlebars", thumbnail: 'handlebars.png' },
    { name: "PHP", thumbnail: 'php.webp' },
    { name: "Laravel", thumbnail: 'laravel.png' },
    { name: "Symfony", thumbnail: 'symfony.webp' },
    { name: "Webpack", thumbnail: 'webpack.webp' },
    { name: "MongoDB", thumbnail: 'mongo.webp' },
    { name: "Firebase", thumbnail: 'firebase.webp' },
    { name: "MySQL", thumbnail: 'mysql.webp' }
]